language: ruby
sudo: false
addons:
  apt:
    packages:
    - ruby-dev
    - libffi-dev
    - libgmp-dev
cache: bundler
rvm:
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
before_install:
  - gem update bundler
script: bundle exec rspec
