language: ruby
sudo: false
addons:
  apt:
    packages:
    - ruby-dev
    - libffi-dev
    - libgmp-dev
cache: bundler
rvm:
  - ruby-2.2.6
  - ruby-2.3.3
  - ruby-2.4.0
  - ruby-head
before_install:
  - gem update --system
  - gem update bundler
script:
  - bundle exec rspec
  - bundle exec rubocop -D
